import type { Metadata } from 'next'

import StyledComponentsRegistry from '@/src/utils/registry';
import Sidebar from '@/src/components/Sidebar/Sidebar'
import { GlobalStyles } from '@/src/styles/GlobalStyles';
import { RootLayoutThemeProvider } from '@/src/utils/providers';
import { ModalProvider } from '@/src/utils/ModalProvider';
import Modal from '@/src/components/Modal/Modal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <RootLayoutThemeProvider>
            <ModalProvider>
              <Sidebar />
              {children}
              <Modal />
              <GlobalStyles />
            </ModalProvider>
          </RootLayoutThemeProvider>
        </StyledComponentsRegistry>
        <div id='modal-root'></div>
      </body>
    </html>
  )
}
